version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      BACKEND_URL: http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/topicsDB
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: topicsDB
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
